### ISSUE TITLE
Question about TendonRobotStatics.m

### ISSUE THREAD

**Issue by feilong926** [JohnDTill/ContinuumRobotExamples#11]
in line 109 of 'TendonRobotStatics.m', you have v0 = Kse\n0 + [0;0;1];
did you neglect R0? I know it does not affect the numerical solution since R0 = eye(3).

**Comment by JohnDTill** [comment]
Rotation is unnecessary since this formulation uses the body frame internal force and moment, which is the same frame as the shear and curvature. This does point out that the naming is misleading; `n0` on lines 108 and 109 should be called `nb0`. Similarly, `nb` defined on line 120 and `mb` on line 121 should be called `nbL` and `mbL`. I will update this, or you are welcome to submit if you prefer. (I don't have a MATLAB license to test changes, but I don't anticipate breaking the script!)

**Comment by feilong926** [comment]
Your explanation about the naming makes sense! Thanks :)

**Comment by JohnDTill** [comment]
Thanks for pointing it out! Those vars have better names after the last push.
